import type { Metadata } from "next";
import { Work_Sans, Oranienbaum, Montagu_Slab } from "next/font/google";

import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ['latin']
});

const oranienbaum = Oranienbaum({
  variable: "--font-oraniembaum-sans",
  weight: "400",
  subsets: ['latin']
});

const montaguSlab = Montagu_Slab({
  variable: "--font-montagu-slab-sans",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Jiahua Cui | Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${oranienbaum.variable} ${montaguSlab.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
